# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\designer\image.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DisplayImage(object):
    def setupUi(self, DisplayImage):
        DisplayImage.setObjectName("DisplayImage")
        DisplayImage.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(DisplayImage)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblImage = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblImage.sizePolicy().hasHeightForWidth())
        self.lblImage.setSizePolicy(sizePolicy)
        self.lblImage.setText("")
        self.lblImage.setScaledContents(True)
        self.lblImage.setObjectName("lblImage")
        self.verticalLayout.addWidget(self.lblImage)
        DisplayImage.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(DisplayImage)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        DisplayImage.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(DisplayImage)
        self.statusbar.setObjectName("statusbar")
        DisplayImage.setStatusBar(self.statusbar)

        self.retranslateUi(DisplayImage)
        QtCore.QMetaObject.connectSlotsByName(DisplayImage)

    def retranslateUi(self, DisplayImage):
        _translate = QtCore.QCoreApplication.translate
        DisplayImage.setWindowTitle(_translate("DisplayImage", "Ảnh vi phạm"))
