# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\designer\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1090, 729)
        MainWindow.setStyleSheet("QMainWindow {\n"
"background-color: #fafafa;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("#centralwidget {\n"
"background-color: #fafafa;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.headerFrame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.headerFrame.sizePolicy().hasHeightForWidth())
        self.headerFrame.setSizePolicy(sizePolicy)
        self.headerFrame.setMaximumSize(QtCore.QSize(16777215, 50))
        self.headerFrame.setStyleSheet("#appTitleLbl {\n"
"font: 20pt;\n"
"font-weight: bold;\n"
"}\n"
"\n"
"QFrame, #btnMenu {\n"
"background-color:  #048CF2;\n"
"}\n"
"\n"
"#btnMenu {\n"
"font-weight: bold;\n"
"font: 15pt;\n"
"border: none;\n"
"}\n"
"\n"
"#btnMenu::checked {\n"
"background-color:  #f7f7f7;\n"
"}\n"
"\n"
"#btnMenu::hover {\n"
"background-color:  #efefef;\n"
"border-bottom: 6px solid #000000;\n"
"}\n"
"\n"
"\n"
"#btnMenu::pressed {\n"
"background-color:  #efefef;\n"
"border-bottom: 2px solid #000000;\n"
"}")
        self.headerFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.headerFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.headerFrame.setObjectName("headerFrame")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.headerFrame)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(10)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.btnMenu = QtWidgets.QPushButton(self.headerFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnMenu.sizePolicy().hasHeightForWidth())
        self.btnMenu.setSizePolicy(sizePolicy)
        self.btnMenu.setMinimumSize(QtCore.QSize(160, 50))
        self.btnMenu.setMaximumSize(QtCore.QSize(160, 50))
        self.btnMenu.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnMenu.setStyleSheet("")
        self.btnMenu.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Menu/icons/menu.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnMenu.setIcon(icon)
        self.btnMenu.setIconSize(QtCore.QSize(32, 32))
        self.btnMenu.setCheckable(True)
        self.btnMenu.setChecked(True)
        self.btnMenu.setAutoDefault(False)
        self.btnMenu.setDefault(False)
        self.btnMenu.setFlat(False)
        self.btnMenu.setObjectName("btnMenu")
        self.horizontalLayout_7.addWidget(self.btnMenu)
        self.appTitleLbl = QtWidgets.QLabel(self.headerFrame)
        font = QtGui.QFont()
        font.setFamily("SF Pro Display")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.appTitleLbl.setFont(font)
        self.appTitleLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.appTitleLbl.setWordWrap(True)
        self.appTitleLbl.setObjectName("appTitleLbl")
        self.horizontalLayout_7.addWidget(self.appTitleLbl)
        self.horizontalLayout_7.setStretch(0, 4)
        self.horizontalLayout_7.setStretch(1, 5)
        self.verticalLayout.addWidget(self.headerFrame)
        self.bodyFrame = QtWidgets.QFrame(self.centralwidget)
        self.bodyFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.bodyFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bodyFrame.setObjectName("bodyFrame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.bodyFrame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.menuBarFrame = QtWidgets.QFrame(self.bodyFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menuBarFrame.sizePolicy().hasHeightForWidth())
        self.menuBarFrame.setSizePolicy(sizePolicy)
        self.menuBarFrame.setMinimumSize(QtCore.QSize(0, 0))
        self.menuBarFrame.setMaximumSize(QtCore.QSize(160, 16777215))
        self.menuBarFrame.setStyleSheet("QFrame, QPushButton {\n"
"background-color:  #f7f7f7;\n"
"color: #000000;\n"
"border: none;\n"
"}\n"
"\n"
"QPushButton {\n"
"padding-left: 10px;\n"
"text-align: left;\n"
"font-weight: bold;\n"
"font: 10pt;\n"
"border-bottom-right-radius: 2px;\n"
"border-bottom: 3px solid black;\n"
"}\n"
"\n"
"QPushButton::checked {\n"
"color: #2f9aff;\n"
"border-bottom-right-radius: 2px;\n"
"background-color:  #efefef;\n"
"border-bottom: 6px solid #2f9aff;\n"
"}\n"
"\n"
"\n"
"QPushButton::hover {\n"
"color: #9bcfff;\n"
"border-bottom-right-radius: 2px;\n"
"background-color:  #efefef;\n"
"border-bottom: 6px solid #9bcfff;\n"
"}\n"
"\n"
"QPushButton::pressed {\n"
"color: #2f9aff;\n"
"border-bottom-right-radius: 2px;\n"
"background-color:  #efefef;\n"
"border-bottom: 2px solid #2f9aff;\n"
"}")
        self.menuBarFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.menuBarFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menuBarFrame.setMidLineWidth(0)
        self.menuBarFrame.setObjectName("menuBarFrame")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.menuBarFrame)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.navBtnFrame = QtWidgets.QFrame(self.menuBarFrame)
        self.navBtnFrame.setMaximumSize(QtCore.QSize(16777215, 400))
        self.navBtnFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.navBtnFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.navBtnFrame.setObjectName("navBtnFrame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.navBtnFrame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btnRegisterUserPage = QtWidgets.QPushButton(self.navBtnFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnRegisterUserPage.sizePolicy().hasHeightForWidth())
        self.btnRegisterUserPage.setSizePolicy(sizePolicy)
        self.btnRegisterUserPage.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btnRegisterUserPage.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Register/icons/register.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnRegisterUserPage.setIcon(icon1)
        self.btnRegisterUserPage.setIconSize(QtCore.QSize(24, 24))
        self.btnRegisterUserPage.setObjectName("btnRegisterUserPage")
        self.verticalLayout_2.addWidget(self.btnRegisterUserPage)
        self.btnSetupPage = QtWidgets.QPushButton(self.navBtnFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSetupPage.sizePolicy().hasHeightForWidth())
        self.btnSetupPage.setSizePolicy(sizePolicy)
        self.btnSetupPage.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btnSetupPage.setFont(font)
        self.btnSetupPage.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnSetupPage.setAutoFillBackground(False)
        self.btnSetupPage.setStyleSheet("font: 10pt \"Segoe UI\";")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Tables/icons/tables.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSetupPage.setIcon(icon2)
        self.btnSetupPage.setIconSize(QtCore.QSize(24, 24))
        self.btnSetupPage.setCheckable(True)
        self.btnSetupPage.setChecked(True)
        self.btnSetupPage.setAutoRepeat(False)
        self.btnSetupPage.setObjectName("btnSetupPage")
        self.verticalLayout_2.addWidget(self.btnSetupPage)
        self.btnLiveStreamPage = QtWidgets.QPushButton(self.navBtnFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnLiveStreamPage.sizePolicy().hasHeightForWidth())
        self.btnLiveStreamPage.setSizePolicy(sizePolicy)
        self.btnLiveStreamPage.setMaximumSize(QtCore.QSize(16777215, 100))
        self.btnLiveStreamPage.setStyleSheet("font: 10pt \"Segoe UI\";")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/LiveStream/icons/live-streaming.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnLiveStreamPage.setIcon(icon3)
        self.btnLiveStreamPage.setIconSize(QtCore.QSize(24, 24))
        self.btnLiveStreamPage.setCheckable(True)
        self.btnLiveStreamPage.setObjectName("btnLiveStreamPage")
        self.verticalLayout_2.addWidget(self.btnLiveStreamPage)
        self.btnViolationPage = QtWidgets.QPushButton(self.navBtnFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnViolationPage.sizePolicy().hasHeightForWidth())
        self.btnViolationPage.setSizePolicy(sizePolicy)
        self.btnViolationPage.setMaximumSize(QtCore.QSize(16777215, 100))
        self.btnViolationPage.setStyleSheet("font: 10pt \"Segoe UI\";")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Violation/icons/violation.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnViolationPage.setIcon(icon4)
        self.btnViolationPage.setIconSize(QtCore.QSize(24, 24))
        self.btnViolationPage.setCheckable(True)
        self.btnViolationPage.setObjectName("btnViolationPage")
        self.verticalLayout_2.addWidget(self.btnViolationPage)
        self.exitButton = QtWidgets.QPushButton(self.navBtnFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exitButton.sizePolicy().hasHeightForWidth())
        self.exitButton.setSizePolicy(sizePolicy)
        self.exitButton.setMinimumSize(QtCore.QSize(0, 0))
        self.exitButton.setMaximumSize(QtCore.QSize(16777215, 100))
        self.exitButton.setStyleSheet("font: 10pt \"Segoe UI\";")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/Exit/icons/power-off.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exitButton.setIcon(icon5)
        self.exitButton.setIconSize(QtCore.QSize(24, 24))
        self.exitButton.setObjectName("exitButton")
        self.verticalLayout_2.addWidget(self.exitButton)
        self.verticalLayout_6.addWidget(self.navBtnFrame)
        self.infoBtnFrame = QtWidgets.QFrame(self.menuBarFrame)
        self.infoBtnFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.infoBtnFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.infoBtnFrame.setObjectName("infoBtnFrame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.infoBtnFrame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_6.addWidget(self.infoBtnFrame)
        self.horizontalLayout_2.addWidget(self.menuBarFrame)
        self.stackedWidget = QtWidgets.QStackedWidget(self.bodyFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setAutoFillBackground(False)
        self.stackedWidget.setStyleSheet("QWidget, QFrame {\n"
"background-color: #efefef;\n"
"}\n"
"\n"
"#serverIPFrame {\n"
"border-bottom: 1px solid #d7efff;\n"
"}\n"
"\n"
"QLabel {\n"
"color: #000000;\n"
"font-weight: bold;\n"
"font: 15px;\n"
"}\n"
"\n"
"QLineEdit, QComboBox, QDateEdit {\n"
"background-color: #FFFFFF;\n"
"border: 1px solid  #b0b0b0;\n"
"border-radius: 4px;\n"
"color: #000000;\n"
"}\n"
"\n"
"QComboBox:focus {\n"
"border: 1px solid  #2f9aff;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"border: 1px solid #b0b0b0;\n"
"color: black;\n"
"selection-background-color: #2f9aff;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"border: 1px solid  #2f9aff;\n"
"}\n"
"\n"
"/* Style DateTime */\n"
"\n"
"QDateEdit QWidget {\n"
"alternate-background-color: #B8E2FF;\n"
"color: #000000;\n"
"}\n"
"\n"
"#qt_calendar_navigationbar {\n"
"background-color: #fff;\n"
"border: 2px solid #b8e2ff;\n"
"border-top-left-radius: 5px;\n"
"border-top-right-radius: 5px;\n"
"}\n"
"\n"
"/* Style month changes */\n"
"#qt_calendar_prevmonth, \n"
"#qt_calendar_nextmonth {\n"
"border: none;\n"
"qproperty-icon: none;\n"
"min-width: 13px;\n"
"max-width: 13px;\n"
"min-height: 13px;\n"
"max-height: 13px;\n"
"border-radius: 5px;\n"
"background-color: transparent;\n"
"padding: 5px;\n"
"}\n"
"\n"
"#qt_calendar_prevmonth {\n"
"margin-right: 5px;\n"
"image: url(:/LeftArrow/icons/arrow-left.png);\n"
"}\n"
"\n"
"#qt_calendar_nextmonth {\n"
"margin-left: 5px;\n"
"image: url(:/RightArrow/icons/arrow-right.png);\n"
"}\n"
"\n"
"#qt_calendar_prevmonth::hover, \n"
"#qt_calendar_nextmonth::hover {\n"
"background-color: #55aaff;\n"
"}\n"
"\n"
"#qt_calendar_prevmonth::pressed, \n"
"#qt_calendar_nextmonth::pressed {\n"
"background-color: #55aaff;\n"
"}\n"
"\n"
"#qt_calendar_yearbutton {\n"
"color: black;\n"
"background-color: white;\n"
"border-radius: 3px;\n"
"font-size: 13px;\n"
"border: 2px solid #b8e2ff;\n"
"}\n"
"\n"
"#qt_calendar_monthbutton {\n"
"width: 100px;\n"
"background-color: white;\n"
"color: black;\n"
"font-size: 13px;\n"
"border-radius: 3px;\n"
"border: 2px solid #b8e2ff;\n"
"}\n"
"\n"
"#qt_calendar_yearbutton::hover,\n"
"#qt_calendar_monthbutton::hover {\n"
"background-color: rgba(235, 235, 235, 100);\n"
"}\n"
"\n"
"#qt_calendar_yearbutton::pressed,\n"
"#qt_calendar_monthbutton::pressed {\n"
"background-color: rgba(235, 235, 235, 100);\n"
"}\n"
"\n"
"#qt_calendar_yearedit {\n"
"min-width: 53px;\n"
"color: black;\n"
"background: transparent;\n"
"font-size: 13px;\n"
"}\n"
"\n"
"QToolButton QMenu {\n"
"background-color: white;\n"
"}\n"
"\n"
"QToolButton QMenu::item:selected:enabled {\n"
"background-color: #55aaff;\n"
"}\n"
"\n"
"#qt_calendar_calendarview {\n"
"border: 2px solid #b8e2ff;\n"
"border-top: 0px;\n"
"border-top-left-radius: 5px;\n"
"border-top-right-radius: 5px;\n"
"}\n"
"\n"
"#qt_calendar_calendarview::item:hover {\n"
"border-radius: 5px;\n"
"background-color: #aaffff;\n"
"}\n"
"\n"
"#qt_calendar_calendarview::item:selected {\n"
"border-radius: 5px;\n"
"background-color: #55aaff;\n"
"}\n"
"\n"
"\n"
"QPushButton {\n"
"border: none;\n"
"border-bottom: 1px solid #b0b0b0;\n"
"background-color: #FFFFFF;\n"
"color: #000000;\n"
"font-weight: bold;\n"
"font: 15px;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"color: #2f9aff;\n"
"border-bottom: 4px solid #2f9aff;\n"
"}\n"
"\n"
"QPushButton::pressed {\n"
"color: #2f9aff;\n"
"border-bottom: 2px solid #2f9aff;\n"
"}\n"
"\n"
"#btnCompactLS::checked {\n"
"color: #2f9aff;\n"
"background-color: #7dc0ff;\n"
"}\n"
"\n"
"QTableView {\n"
"background-color: #FFFFFF;\n"
"color: black;\n"
"border: 1px solid  #b0b0b0;\n"
"border-radius: 10px;\n"
"font: 15px;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"background-color:  #d8f8ff;\n"
"color: black;\n"
"border: 1px solid  #b0b0b0;\n"
"}")
        self.stackedWidget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.stackedWidget.setMidLineWidth(0)
        self.stackedWidget.setObjectName("stackedWidget")
        self.RegisterWidget = QtWidgets.QWidget()
        self.RegisterWidget.setObjectName("RegisterWidget")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.RegisterWidget)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.RegisterLabel = QtWidgets.QLabel(self.RegisterWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RegisterLabel.sizePolicy().hasHeightForWidth())
        self.RegisterLabel.setSizePolicy(sizePolicy)
        self.RegisterLabel.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.RegisterLabel.setFont(font)
        self.RegisterLabel.setStyleSheet("font: 16pt \"Segoe UI\";")
        self.RegisterLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.RegisterLabel.setObjectName("RegisterLabel")
        self.verticalLayout_10.addWidget(self.RegisterLabel)
        self.RegisterCameraLabel = QtWidgets.QLabel(self.RegisterWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RegisterCameraLabel.sizePolicy().hasHeightForWidth())
        self.RegisterCameraLabel.setSizePolicy(sizePolicy)
        self.RegisterCameraLabel.setText("")
        self.RegisterCameraLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.RegisterCameraLabel.setObjectName("RegisterCameraLabel")
        self.verticalLayout_10.addWidget(self.RegisterCameraLabel)
        self.stackedWidget.addWidget(self.RegisterWidget)
        self.setupWidget = QtWidgets.QWidget()
        self.setupWidget.setAutoFillBackground(False)
        self.setupWidget.setObjectName("setupWidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.setupWidget)
        self.verticalLayout_5.setContentsMargins(-1, 0, 10, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.serverIPFrame = QtWidgets.QFrame(self.setupWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.serverIPFrame.sizePolicy().hasHeightForWidth())
        self.serverIPFrame.setSizePolicy(sizePolicy)
        self.serverIPFrame.setMinimumSize(QtCore.QSize(700, 30))
        self.serverIPFrame.setMaximumSize(QtCore.QSize(700, 30))
        self.serverIPFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.serverIPFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.serverIPFrame.setObjectName("serverIPFrame")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.serverIPFrame)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(5)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.serverIPLbl = QtWidgets.QLabel(self.serverIPFrame)
        self.serverIPLbl.setMinimumSize(QtCore.QSize(80, 20))
        self.serverIPLbl.setMaximumSize(QtCore.QSize(80, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.serverIPLbl.setFont(font)
        self.serverIPLbl.setStyleSheet("font: 12pt \"Segoe UI\";")
        self.serverIPLbl.setObjectName("serverIPLbl")
        self.horizontalLayout_8.addWidget(self.serverIPLbl)
        self.comboBoxServerIP = QtWidgets.QComboBox(self.serverIPFrame)
        self.comboBoxServerIP.setMinimumSize(QtCore.QSize(500, 0))
        self.comboBoxServerIP.setMaximumSize(QtCore.QSize(500, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.comboBoxServerIP.setFont(font)
        self.comboBoxServerIP.setStyleSheet("font: 12pt \"Segoe UI\";")
        self.comboBoxServerIP.setEditable(True)
        self.comboBoxServerIP.setObjectName("comboBoxServerIP")
        self.horizontalLayout_8.addWidget(self.comboBoxServerIP, 0, QtCore.Qt.AlignHCenter)
        self.checkButton = QtWidgets.QPushButton(self.serverIPFrame)
        self.checkButton.setMinimumSize(QtCore.QSize(100, 25))
        self.checkButton.setMaximumSize(QtCore.QSize(100, 25))
        self.checkButton.setStyleSheet("font: 12pt \"Segoe UI\";")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/Tick/icons/correct.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.checkButton.setIcon(icon6)
        self.checkButton.setObjectName("checkButton")
        self.horizontalLayout_8.addWidget(self.checkButton)
        self.verticalLayout_5.addWidget(self.serverIPFrame, 0, QtCore.Qt.AlignHCenter)
        self.searchBarFrame = QtWidgets.QFrame(self.setupWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchBarFrame.sizePolicy().hasHeightForWidth())
        self.searchBarFrame.setSizePolicy(sizePolicy)
        self.searchBarFrame.setMinimumSize(QtCore.QSize(0, 30))
        self.searchBarFrame.setMaximumSize(QtCore.QSize(16777215, 40))
        self.searchBarFrame.setStyleSheet("")
        self.searchBarFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.searchBarFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.searchBarFrame.setObjectName("searchBarFrame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.searchBarFrame)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.searchLbl = QtWidgets.QLabel(self.searchBarFrame)
        self.searchLbl.setStyleSheet("font: 12pt \"Segoe UI\";")
        self.searchLbl.setObjectName("searchLbl")
        self.horizontalLayout_4.addWidget(self.searchLbl, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableSearch = QtWidgets.QLineEdit(self.searchBarFrame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tableSearch.setFont(font)
        self.tableSearch.setObjectName("tableSearch")
        self.horizontalLayout_4.addWidget(self.tableSearch)
        self.label = QtWidgets.QLabel(self.searchBarFrame)
        self.label.setStyleSheet("font: 12pt \"Segoe UI\";")
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.tableFieldCB = QtWidgets.QComboBox(self.searchBarFrame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tableFieldCB.setFont(font)
        self.tableFieldCB.setObjectName("tableFieldCB")
        self.horizontalLayout_4.addWidget(self.tableFieldCB)
        self.horizontalLayout_4.setStretch(1, 8)
        self.horizontalLayout_4.setStretch(3, 2)
        self.verticalLayout_5.addWidget(self.searchBarFrame)
        self.tableFrame = QtWidgets.QFrame(self.setupWidget)
        self.tableFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tableFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tableFrame.setObjectName("tableFrame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tableFrame)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.setupTableView = QtWidgets.QTableView(self.tableFrame)
        self.setupTableView.setMinimumSize(QtCore.QSize(0, 300))
        self.setupTableView.setStyleSheet("font: 12pt \"Segoe UI\";")
        self.setupTableView.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.setupTableView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.setupTableView.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.setupTableView.setSortingEnabled(False)
        self.setupTableView.setObjectName("setupTableView")
        self.setupTableView.verticalHeader().setVisible(False)
        self.verticalLayout_4.addWidget(self.setupTableView)
        self.btnTableFrame = QtWidgets.QFrame(self.tableFrame)
        self.btnTableFrame.setMaximumSize(QtCore.QSize(120, 60))
        self.btnTableFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.btnTableFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.btnTableFrame.setObjectName("btnTableFrame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.btnTableFrame)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(3)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.btnAddRow = QtWidgets.QPushButton(self.btnTableFrame)
        self.btnAddRow.setMinimumSize(QtCore.QSize(50, 30))
        self.btnAddRow.setMaximumSize(QtCore.QSize(50, 30))
        self.btnAddRow.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/Add/icons/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAddRow.setIcon(icon7)
        self.btnAddRow.setIconSize(QtCore.QSize(20, 20))
        self.btnAddRow.setObjectName("btnAddRow")
        self.horizontalLayout_5.addWidget(self.btnAddRow)
        self.btnDelRow = QtWidgets.QPushButton(self.btnTableFrame)
        self.btnDelRow.setMinimumSize(QtCore.QSize(50, 30))
        self.btnDelRow.setMaximumSize(QtCore.QSize(50, 30))
        self.btnDelRow.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/Delete/icons/minimize-sign.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnDelRow.setIcon(icon8)
        self.btnDelRow.setIconSize(QtCore.QSize(20, 20))
        self.btnDelRow.setObjectName("btnDelRow")
        self.horizontalLayout_5.addWidget(self.btnDelRow)
        self.verticalLayout_4.addWidget(self.btnTableFrame)
        self.verticalLayout_4.setStretch(0, 8)
        self.verticalLayout_5.addWidget(self.tableFrame)
        self.btnFileFrame = QtWidgets.QFrame(self.setupWidget)
        self.btnFileFrame.setMaximumSize(QtCore.QSize(700, 16777215))
        self.btnFileFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.btnFileFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.btnFileFrame.setObjectName("btnFileFrame")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.btnFileFrame)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(30)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.btnOpenFile = QtWidgets.QPushButton(self.btnFileFrame)
        self.btnOpenFile.setMinimumSize(QtCore.QSize(100, 30))
        self.btnOpenFile.setMaximumSize(QtCore.QSize(100, 90))
        self.btnOpenFile.setStyleSheet("font: 12pt \"Segoe UI\";")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/Open/icons/open_folder.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnOpenFile.setIcon(icon9)
        self.btnOpenFile.setObjectName("btnOpenFile")
        self.horizontalLayout_6.addWidget(self.btnOpenFile)
        self.btnSelectROI = QtWidgets.QPushButton(self.btnFileFrame)
        self.btnSelectROI.setMinimumSize(QtCore.QSize(130, 30))
        self.btnSelectROI.setMaximumSize(QtCore.QSize(130, 30))
        self.btnSelectROI.setStyleSheet("font: 12pt \"Segoe UI\";")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/Select_ROI/icons/select_roi.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSelectROI.setIcon(icon10)
        self.btnSelectROI.setObjectName("btnSelectROI")
        self.horizontalLayout_6.addWidget(self.btnSelectROI)
        self.btnExportFile = QtWidgets.QPushButton(self.btnFileFrame)
        self.btnExportFile.setMinimumSize(QtCore.QSize(100, 30))
        self.btnExportFile.setMaximumSize(QtCore.QSize(100, 90))
        self.btnExportFile.setStyleSheet("font: 12pt \"Segoe UI\";")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/Save/icons/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnExportFile.setIcon(icon11)
        self.btnExportFile.setObjectName("btnExportFile")
        self.horizontalLayout_6.addWidget(self.btnExportFile)
        self.btnLive = QtWidgets.QPushButton(self.btnFileFrame)
        self.btnLive.setMinimumSize(QtCore.QSize(100, 30))
        self.btnLive.setMaximumSize(QtCore.QSize(100, 90))
        self.btnLive.setStyleSheet("font: 12pt \"Segoe UI\";")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/Execute/icons/execute.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnLive.setIcon(icon12)
        self.btnLive.setObjectName("btnLive")
        self.horizontalLayout_6.addWidget(self.btnLive)
        self.verticalLayout_5.addWidget(self.btnFileFrame, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_5.setStretch(1, 1)
        self.stackedWidget.addWidget(self.setupWidget)
        self.livestreamWidget = QtWidgets.QWidget()
        self.livestreamWidget.setObjectName("livestreamWidget")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.livestreamWidget)
        self.verticalLayout_8.setContentsMargins(0, 4, 0, 0)
        self.verticalLayout_8.setSpacing(4)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.btnGridModeFrame = QtWidgets.QFrame(self.livestreamWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnGridModeFrame.sizePolicy().hasHeightForWidth())
        self.btnGridModeFrame.setSizePolicy(sizePolicy)
        self.btnGridModeFrame.setMinimumSize(QtCore.QSize(300, 30))
        self.btnGridModeFrame.setMaximumSize(QtCore.QSize(300, 30))
        self.btnGridModeFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.btnGridModeFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.btnGridModeFrame.setObjectName("btnGridModeFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.btnGridModeFrame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnCompactLS = QtWidgets.QPushButton(self.btnGridModeFrame)
        self.btnCompactLS.setMinimumSize(QtCore.QSize(40, 25))
        self.btnCompactLS.setMaximumSize(QtCore.QSize(40, 25))
        self.btnCompactLS.setText("")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/GridLayout/icons/grid_layout_comp_2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnCompactLS.setIcon(icon13)
        self.btnCompactLS.setIconSize(QtCore.QSize(18, 18))
        self.btnCompactLS.setCheckable(True)
        self.btnCompactLS.setObjectName("btnCompactLS")
        self.horizontalLayout.addWidget(self.btnCompactLS)
        self.startLiveButton = QtWidgets.QPushButton(self.btnGridModeFrame)
        self.startLiveButton.setMinimumSize(QtCore.QSize(0, 25))
        self.startLiveButton.setStyleSheet("font: 12pt \"Segoe UI\";")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/Play_Live/icons/play_button.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.startLiveButton.setIcon(icon14)
        self.startLiveButton.setObjectName("startLiveButton")
        self.horizontalLayout.addWidget(self.startLiveButton)
        self.stopLiveButton = QtWidgets.QPushButton(self.btnGridModeFrame)
        self.stopLiveButton.setMinimumSize(QtCore.QSize(0, 25))
        self.stopLiveButton.setStyleSheet("font: 12pt \"Segoe UI\";")
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/Stop_Live/icons/stop_button.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stopLiveButton.setIcon(icon15)
        self.stopLiveButton.setObjectName("stopLiveButton")
        self.horizontalLayout.addWidget(self.stopLiveButton)
        self.verticalLayout_8.addWidget(self.btnGridModeFrame)
        self.scrollAreaGrid = QtWidgets.QScrollArea(self.livestreamWidget)
        self.scrollAreaGrid.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollAreaGrid.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.scrollAreaGrid.setWidgetResizable(True)
        self.scrollAreaGrid.setObjectName("scrollAreaGrid")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 928, 597))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.LiveStreamGrid = QtWidgets.QGridLayout()
        self.LiveStreamGrid.setSpacing(1)
        self.LiveStreamGrid.setObjectName("LiveStreamGrid")
        self.verticalLayout_7.addLayout(self.LiveStreamGrid)
        self.scrollAreaGrid.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_8.addWidget(self.scrollAreaGrid)
        self.stackedWidget.addWidget(self.livestreamWidget)
        self.violationWidget = QtWidgets.QWidget()
        self.violationWidget.setObjectName("violationWidget")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.violationWidget)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.filterBarFrameVio = QtWidgets.QFrame(self.violationWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filterBarFrameVio.sizePolicy().hasHeightForWidth())
        self.filterBarFrameVio.setSizePolicy(sizePolicy)
        self.filterBarFrameVio.setMinimumSize(QtCore.QSize(800, 50))
        self.filterBarFrameVio.setMaximumSize(QtCore.QSize(10000000, 50))
        self.filterBarFrameVio.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.filterBarFrameVio.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.filterBarFrameVio.setFrameShadow(QtWidgets.QFrame.Raised)
        self.filterBarFrameVio.setObjectName("filterBarFrameVio")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.filterBarFrameVio)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setSpacing(20)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.fromFilterFrameVio = QtWidgets.QFrame(self.filterBarFrameVio)
        self.fromFilterFrameVio.setMinimumSize(QtCore.QSize(0, 30))
        self.fromFilterFrameVio.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.fromFilterFrameVio.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fromFilterFrameVio.setObjectName("fromFilterFrameVio")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.fromFilterFrameVio)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setSpacing(4)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.fromLabelVio = QtWidgets.QLabel(self.fromFilterFrameVio)
        self.fromLabelVio.setMinimumSize(QtCore.QSize(50, 25))
        self.fromLabelVio.setMaximumSize(QtCore.QSize(50, 25))
        self.fromLabelVio.setStyleSheet("font: 12pt \"Segoe UI\";")
        self.fromLabelVio.setAlignment(QtCore.Qt.AlignCenter)
        self.fromLabelVio.setObjectName("fromLabelVio")
        self.horizontalLayout_13.addWidget(self.fromLabelVio)
        self.fromHourEditVio = QtWidgets.QComboBox(self.fromFilterFrameVio)
        self.fromHourEditVio.setMinimumSize(QtCore.QSize(0, 25))
        self.fromHourEditVio.setMaximumSize(QtCore.QSize(16777215, 25))
        self.fromHourEditVio.setStyleSheet("font: 12pt \"Segoe UI\";")
        self.fromHourEditVio.setObjectName("fromHourEditVio")
        self.horizontalLayout_13.addWidget(self.fromHourEditVio)
        self.fromMinuteEditVio = QtWidgets.QComboBox(self.fromFilterFrameVio)
        self.fromMinuteEditVio.setMinimumSize(QtCore.QSize(0, 25))
        self.fromMinuteEditVio.setMaximumSize(QtCore.QSize(16777215, 25))
        self.fromMinuteEditVio.setStyleSheet("font: 12pt \"Segoe UI\";")
        self.fromMinuteEditVio.setObjectName("fromMinuteEditVio")
        self.horizontalLayout_13.addWidget(self.fromMinuteEditVio)
        self.fromDateEditVio = QtWidgets.QDateEdit(self.fromFilterFrameVio)
        self.fromDateEditVio.setMinimumSize(QtCore.QSize(0, 25))
        self.fromDateEditVio.setMaximumSize(QtCore.QSize(16777215, 25))
        self.fromDateEditVio.setStyleSheet("font: 12pt \"Segoe UI\";")
        self.fromDateEditVio.setCalendarPopup(True)
        self.fromDateEditVio.setObjectName("fromDateEditVio")
        self.horizontalLayout_13.addWidget(self.fromDateEditVio)
        self.horizontalLayout_12.addWidget(self.fromFilterFrameVio)
        self.toFilterFrameVio = QtWidgets.QFrame(self.filterBarFrameVio)
        self.toFilterFrameVio.setMinimumSize(QtCore.QSize(0, 30))
        self.toFilterFrameVio.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.toFilterFrameVio.setFrameShadow(QtWidgets.QFrame.Raised)
        self.toFilterFrameVio.setObjectName("toFilterFrameVio")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.toFilterFrameVio)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setSpacing(4)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.toLabelVio = QtWidgets.QLabel(self.toFilterFrameVio)
        self.toLabelVio.setMinimumSize(QtCore.QSize(50, 25))
        self.toLabelVio.setMaximumSize(QtCore.QSize(50, 25))
        self.toLabelVio.setStyleSheet("font: 12pt \"Segoe UI\";")
        self.toLabelVio.setAlignment(QtCore.Qt.AlignCenter)
        self.toLabelVio.setObjectName("toLabelVio")
        self.horizontalLayout_14.addWidget(self.toLabelVio)
        self.toHourEditVio = QtWidgets.QComboBox(self.toFilterFrameVio)
        self.toHourEditVio.setMinimumSize(QtCore.QSize(0, 25))
        self.toHourEditVio.setMaximumSize(QtCore.QSize(16777215, 25))
        self.toHourEditVio.setStyleSheet("font: 12pt \"Segoe UI\";")
        self.toHourEditVio.setObjectName("toHourEditVio")
        self.horizontalLayout_14.addWidget(self.toHourEditVio)
        self.toMinuteEditVio = QtWidgets.QComboBox(self.toFilterFrameVio)
        self.toMinuteEditVio.setMinimumSize(QtCore.QSize(0, 25))
        self.toMinuteEditVio.setMaximumSize(QtCore.QSize(16777215, 25))
        self.toMinuteEditVio.setStyleSheet("font: 12pt \"Segoe UI\";")
        self.toMinuteEditVio.setObjectName("toMinuteEditVio")
        self.horizontalLayout_14.addWidget(self.toMinuteEditVio)
        self.toDateEditVio = QtWidgets.QDateEdit(self.toFilterFrameVio)
        self.toDateEditVio.setMinimumSize(QtCore.QSize(0, 25))
        self.toDateEditVio.setMaximumSize(QtCore.QSize(16777215, 25))
        self.toDateEditVio.setStyleSheet("font: 12pt \"Segoe UI\";")
        self.toDateEditVio.setCalendarPopup(True)
        self.toDateEditVio.setObjectName("toDateEditVio")
        self.horizontalLayout_14.addWidget(self.toDateEditVio)
        self.horizontalLayout_12.addWidget(self.toFilterFrameVio)
        self.btnFilterVio = QtWidgets.QPushButton(self.filterBarFrameVio)
        self.btnFilterVio.setMinimumSize(QtCore.QSize(75, 25))
        self.btnFilterVio.setMaximumSize(QtCore.QSize(75, 25))
        self.btnFilterVio.setStyleSheet("font: 12pt \"Segoe UI\";")
        self.btnFilterVio.setObjectName("btnFilterVio")
        self.horizontalLayout_12.addWidget(self.btnFilterVio)
        self.labelLoading = QtWidgets.QLabel(self.filterBarFrameVio)
        self.labelLoading.setStyleSheet("font: 12pt \"Segoe UI\";")
        self.labelLoading.setObjectName("labelLoading")
        self.horizontalLayout_12.addWidget(self.labelLoading)
        self.verticalLayout_15.addWidget(self.filterBarFrameVio, 0, QtCore.Qt.AlignHCenter)
        self.tabWidgetVio = QtWidgets.QTabWidget(self.violationWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tabWidgetVio.setFont(font)
        self.tabWidgetVio.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidgetVio.setAutoFillBackground(False)
        self.tabWidgetVio.setStyleSheet("QTabBar::tab {\n"
"    color: black;\n"
"}\n"
"QTabBar::tab::selected {\n"
"    background: rgb(4, 190, 103);\n"
"    color: white;\n"
"}\n"
"font: 12pt \"Segoe UI\";\n"
"")
        self.tabWidgetVio.setTabPosition(QtWidgets.QTabWidget.South)
        self.tabWidgetVio.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidgetVio.setDocumentMode(False)
        self.tabWidgetVio.setTabsClosable(False)
        self.tabWidgetVio.setMovable(True)
        self.tabWidgetVio.setTabBarAutoHide(False)
        self.tabWidgetVio.setObjectName("tabWidgetVio")
        self.pageTableVio = QtWidgets.QWidget()
        self.pageTableVio.setObjectName("pageTableVio")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.pageTableVio)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.searchBarFrame_2 = QtWidgets.QFrame(self.pageTableVio)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchBarFrame_2.sizePolicy().hasHeightForWidth())
        self.searchBarFrame_2.setSizePolicy(sizePolicy)
        self.searchBarFrame_2.setMinimumSize(QtCore.QSize(0, 50))
        self.searchBarFrame_2.setMaximumSize(QtCore.QSize(16777215, 40))
        self.searchBarFrame_2.setStyleSheet("")
        self.searchBarFrame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.searchBarFrame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.searchBarFrame_2.setObjectName("searchBarFrame_2")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.searchBarFrame_2)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setSpacing(5)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.searchLbl_Vio = QtWidgets.QLabel(self.searchBarFrame_2)
        self.searchLbl_Vio.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.searchLbl_Vio.setObjectName("searchLbl_Vio")
        self.horizontalLayout_15.addWidget(self.searchLbl_Vio, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableSearch_Vio = QtWidgets.QLineEdit(self.searchBarFrame_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tableSearch_Vio.setFont(font)
        self.tableSearch_Vio.setObjectName("tableSearch_Vio")
        self.horizontalLayout_15.addWidget(self.tableSearch_Vio)
        self.label_filter_vio = QtWidgets.QLabel(self.searchBarFrame_2)
        self.label_filter_vio.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label_filter_vio.setObjectName("label_filter_vio")
        self.horizontalLayout_15.addWidget(self.label_filter_vio)
        self.tableFieldCB_Vio = QtWidgets.QComboBox(self.searchBarFrame_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tableFieldCB_Vio.setFont(font)
        self.tableFieldCB_Vio.setObjectName("tableFieldCB_Vio")
        self.horizontalLayout_15.addWidget(self.tableFieldCB_Vio)
        self.horizontalLayout_15.setStretch(1, 8)
        self.horizontalLayout_15.setStretch(3, 2)
        self.verticalLayout_12.addWidget(self.searchBarFrame_2)
        self.violationTableView = QtWidgets.QTableView(self.pageTableVio)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.violationTableView.setFont(font)
        self.violationTableView.setStyleSheet("font: 12pt \"Segoe UI\";")
        self.violationTableView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.violationTableView.setSortingEnabled(True)
        self.violationTableView.setObjectName("violationTableView")
        self.violationTableView.horizontalHeader().setHighlightSections(False)
        self.violationTableView.verticalHeader().setCascadingSectionResizes(False)
        self.violationTableView.verticalHeader().setHighlightSections(False)
        self.violationTableView.verticalHeader().setSortIndicatorShown(True)
        self.verticalLayout_12.addWidget(self.violationTableView)
        self.tabWidgetVio.addTab(self.pageTableVio, "")
        self.verticalLayout_15.addWidget(self.tabWidgetVio)
        self.verticalLayout_15.setStretch(0, 2)
        self.stackedWidget.addWidget(self.violationWidget)
        self.horizontalLayout_2.addWidget(self.stackedWidget)
        self.verticalLayout.addWidget(self.bodyFrame)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 9)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1090, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        self.tabWidgetVio.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.appTitleLbl.setText(_translate("MainWindow", "MANAGEMENT SYSTEM"))
        self.btnRegisterUserPage.setText(_translate("MainWindow", "ĐĂNG KÝ USER"))
        self.btnSetupPage.setText(_translate("MainWindow", "KHỞI TẠO CAMERA"))
        self.btnLiveStreamPage.setText(_translate("MainWindow", "  LIVESTREAM"))
        self.btnViolationPage.setText(_translate("MainWindow", "  VI PHẠM"))
        self.exitButton.setText(_translate("MainWindow", "THOÁT "))
        self.RegisterLabel.setText(_translate("MainWindow", "Đăng ký User mới"))
        self.serverIPLbl.setText(_translate("MainWindow", "Server IP"))
        self.checkButton.setText(_translate("MainWindow", "Check"))
        self.searchLbl.setText(_translate("MainWindow", "Tìm kiếm"))
        self.label.setText(_translate("MainWindow", "Lọc"))
        self.btnOpenFile.setText(_translate("MainWindow", "Mở File"))
        self.btnSelectROI.setText(_translate("MainWindow", "Chọn vùng ROI"))
        self.btnExportFile.setText(_translate("MainWindow", "Lưu File"))
        self.btnLive.setText(_translate("MainWindow", "CHẠY"))
        self.startLiveButton.setText(_translate("MainWindow", "START"))
        self.stopLiveButton.setText(_translate("MainWindow", "STOP"))
        self.fromLabelVio.setText(_translate("MainWindow", "Từ:"))
        self.toLabelVio.setText(_translate("MainWindow", "Đến:"))
        self.btnFilterVio.setText(_translate("MainWindow", "Tìm kiếm"))
        self.labelLoading.setText(_translate("MainWindow", "Loading..."))
        self.searchLbl_Vio.setText(_translate("MainWindow", "Tìm kiếm"))
        self.label_filter_vio.setText(_translate("MainWindow", "Lọc"))
        self.tabWidgetVio.setTabText(self.tabWidgetVio.indexOf(self.pageTableVio), _translate("MainWindow", "DANH SÁCH VI PHẠM"))
import resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
